---
title: "Pitching yorkpy ... on the middle and outside off stump to IPL - Part 2"
author: "Tinniam V Ganesh"
date: "Dec 27, 2018"
output:
  html_document: default
  word_document: default
---




##**Introduction**

This post is a follow-up to my previous post, [Pitching yorkpy...short of good length to IPL-Part 1](https://gigadom.in/2018/12/28/pitching-yorkpy-short-of-good-length-to-ipl-part-1/), in which I analyzed individual IPL matches. In this 2nd post I analyze the data in all matches between any 2 IPL teams, say CSK-RCB, MI-KKR or DD-RPS and so on. As I have already mentioned **yorky** is the python clone of my R packkage **yorkr** and this post is almost a mirror image of my post with yorkr namely [yorkr crashes the IPL party! - Part 2](https://gigadom.in/2016/04/20/yorkr-crashes-the-ipl-party-part-2/). The signatures of yorkpy and yorkr are identical and will work in amost the same way.


You can clone/download the code at Github [yorkpy](https://github.com/tvganesh/yorkpy)

This post has been published to RPubs at [yorkpy-Part1](http://rpubs.com/tvganesh/454443)

You can download this post as PDF at [IPLT20-yorkpy-part1](https://drive.google.com/file/d/167fSf64L_CkmuWHi-uzN1ceENF3AEOEh/view?usp=sharing)

The IPL T20 functions in yorkpy are 

###1. Functions related to head-to-head confrontations between any 2 IPL teams
The following function can be used to analyze the IPL team performance in a  T20 match

a. getAllMatchesBetweenTeams()
b. saveAllMatchesBetween2IPLTeams()
c. teamBatsmenPartnershiOppnAllMatches()
d. teamBatsmenPartnershipOppnAllMatchesChart()
e. teamBatsmenVsBowlersOppnAllMatches()
f. teamBattingScorecardOppnAllMatches()
g. teamBowlingScorecardOppnAllMatches()
h. teamBowlingWicketKindOppositionAllMatches()
i. teamBowlersVsBatsmenOppnAllMatches()
j. plotWinLossBetweenTeams()
k. plotWinsByRunOrWickets()
l. plotWinsbyTossDecision()

All functions relate to the performance of an IPL team in all matches against an opposing IPL team

## 2. Get data for all T20 matches between 2 teams
We can get all IPL T20 matches between any 2 teams using the function below. The dir parameter should point to the folder which has the IPL T20  csv files of the individual matches (see [Pitching yorkpy...short of good length to IPL-Part 1](https://gigadom.in/2018/12/28/pitching-yorkpy-short-of-good-length-to-ipl-part-1/)). This function creates a data frame of all the IPL T20 matches and and also saves the dataframe as CSV file if save=True. If save=False the dataframe is just returned and not saved.
```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
#dir1= "C:\\software\\cricket-package\\yorkpyPkg\\yorkpyData\\IPLConverted"
#yka.getAllMatchesBetweenTeams("Kolkata Knight Riders","Delhi Daredevils",dir=dir1,save=True)
```

###3. Save data for all matches between all combination of 2 teams
This can be done locally using the function below. You could use this function to combine all IPL Twenty20 matches between any 2 IPL teams into a single dataframe and save it in the current folder. All the dataframes for all combinations have already been done and are available as CSV files in Github

```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
#dir1= "C:\\software\\cricket-package\\yorkpyPkg\\yorkpyData\\IPLConverted"
#yka.saveAllMatchesBetween2IPLTeams(dir1)
```


**Note:** In the functions below, I have randomly chosen any 2 IPL teams and analyze how the teams have performed against each other in different areas. You are free to choose any 2 cpmbination of IPL teams for your analysis

###4.Team Batsmen partnership in Twenty20 (all matches with opposing IPL team - summary)
The function below computes the highest partnerships between the 2 IPL teams Chennai Superkings and Delhi Daredevils. Any other 2 IPL team could have also been chosen. The summary gives the top 3 batsmen for Delhi Daredevils namely Sehwag, Gambhir and Dinesh Karthik when the report='summary'


```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Chennai Super Kings-Delhi Daredevils-allMatches.csv")
csk_dd_matches = pd.read_csv(path)
m=yka.teamBatsmenPartnershiOppnAllMatches(csk_dd_matches,'Delhi Daredevils',report="summary")
print(m)


```
##5. Team Batsmen partnership in Twenty20 (all matches with opposing IPL team -detailed)
The function below gives the detailed breakup of partnerships between Deccan Chargers and Mumbai Indians for Deccan Chargers.

```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Deccan Chargers-Mumbai Indians-allMatches.csv")
dc_mi_matches = pd.read_csv(path)
theTeam='Deccan Chargers'
m=yka.teamBatsmenPartnershiOppnAllMatches(dc_mi_matches,theTeam,report="detailed", top=4)
print(m)
```

##6. Team Batsmen partnership in Twenty20 - Chart (all matches with opposing IPL team)
The function below plots the partnerships in all matches between 2 IPL teams and plots as chart

```{python partnership,cache=TRUE,fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Gujarat Lions-Kings XI Punjab-allMatches.csv")
gl_kxip_matches = pd.read_csv(path)
yka.teamBatsmenPartnershipOppnAllMatchesChart(gl_kxip_matches,'Kings XI Punjab','Gujarat Lions', plot=True, top=4, partnershipRuns=20)
```


##7.Team Batsmen partnership in Twenty20 - Dataframe (all matches with opposing IPL team)

This function does not plot the data but returns the dataframe to the user to plot
or manipulate.

**Note**: Many of the plots include an additional parameters for e.g. plot which is either True or False. The default value is plot=True. When plot=True the plot will be displayed. When plot=False the data frame will be returned to the user. The user can use this to create an interactive charts. The parameter top= specifies the number of top batsmen that need to be included in the chart, and partnershipRuns gives the minimum cutoff runs in partnwerships to be considered

```{python }
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Kolkata Knight Riders-Rising Pune Supergiants-allMatches.csv")
kkr_rps_matches = pd.read_csv(path)
m=yka.teamBatsmenPartnershipOppnAllMatchesChart(kkr_rps_matches,'Rising Pune Supergiants','Kolkata Knight Riders', plot=False, top=5, partnershipRuns=20)
print(m)

```

##8.  Team batsmen versus bowler in Twenty20-Chart (all matches with opposing IPL team)
The plots below provide information on how each of the top batsmen of the IPL teams fared against the opposition bowlers
```{python batsmenVsBowler,cache=TRUE,fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Rajasthan Royals-Royal Challengers Bangalore-allMatches.csv")
rr_rcb_matches = pd.read_csv(path)
yka.teamBatsmenVsBowlersOppnAllMatches(rr_rcb_matches,'Rajasthan Royals',"Royal Challengers Bangalore",plot=True,top=3,runsScored=20)

```

##9 Team batsmen versus bowler in Twenty20-Dataframe (all matches with opposing IPL team)
This function provides the bowling performance, the number of overs bowled,
maidens, runs conceded. wickets taken and economy rate for  the IPL match
```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Mumbai Indians-Delhi Daredevils-allMatches.csv")
mi_dd_matches = pd.read_csv(path)
m=yka.teamBatsmenVsBowlersOppnAllMatches(mi_dd_matches,'Delhi Daredevils',"Mumbai Indians",plot=False,top=2,runsScored=50)
print(m)

```

##10. Team batting scorecard(all matches with opposing IPL team)
This function provides the overall scorecard for an IPL team in all matches against another IPL team. In the snippet below the batting scorecard of RCB is show against CSK. Kohli, Gayle and De villiers lead the pack.
```{python }
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Royal Challengers Bangalore-Chennai Super Kings-allMatches.csv")
rcb_csk_matches = pd.read_csv(path)
scorecard=yka.teamBattingScorecardOppnAllMatches(rcb_csk_matches,'Royal Challengers Bangalore',"Chennai Super Kings")
print(scorecard)


```

##11.Team Bowling scorecard (all matches with opposing IPL team)
The output below gives the performance of Rajasthan Royals bowlers against Kolkata Knight Riders in all matches between the 2 IPL teams.
```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Kolkata Knight Riders-Rajasthan Royals-allMatches.csv")
rcb_csk_matches = pd.read_csv(path)
scorecard=yka.teamBowlingScorecardOppnAllMatches(rcb_csk_matches,'Rajasthan Royals',"Kolkata Knight Riders")
print(scorecard)
```

###12. Team Bowling wicket kind -Chart (all matches with opposing IPL team)
The functions compute and display the kind of wickets taken(bowled, caught, lbw etc) by an IPL team in all matches against another IPL team

```{python bowlerWicketKind,cache=TRUE,fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Chennai Super Kings-Rajasthan Royals-allMatches.csv")
csk_rr_matches = pd.read_csv(path)
yka.teamBowlingWicketKindOppositionAllMatches(csk_rr_matches,'Chennai Super Kings','Rajasthan Royals',plot=True,top=5,wickets=1)


```


###13. Team Bowling wicket kind -Dataframe (all matches with opposing IPL team)
This gives the type of wickets taken
```{python }
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Delhi Daredevils-Pune Warriors-allMatches.csv")
dd_pw_matches = pd.read_csv(path)
m=yka.teamBowlingWicketKindOppositionAllMatches(dd_pw_matches,'Pune Warriors','Delhi Daredevils',plot=False,top=4,wickets=1)
print(m)

```



##14 Team Bowler vs Batman -Plot (all matches with opposing IPL team)
The function below gives the performance of bowlers in all matches against another
IPL team.
```{python bowlerVsBatsmen,cache=TRUE,fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Sunrisers Hyderabad-Kolkata Knight Riders-allMatches.csv")
srh_kkr_matches = pd.read_csv(path)
yka.teamBowlersVsBatsmenOppnAllMatches(srh_kkr_matches,'Sunrisers Hyderabad','Kolkata Knight Riders',plot=True,top=5,runsConceded=10)
```

## 15 Team Bowler vs Batman - Dataframe (all matches with opposing IPL team)
```{python}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Royal Challengers Bangalore-Kings XI Punjab-allMatches.csv")
srh_kkr_matches = pd.read_csv(path)
m=yka.teamBowlersVsBatsmenOppnAllMatches(srh_kkr_matches,'Royal Challengers Bangalore','Kings XI Punjab',plot=False,top=1,runsConceded=30)
print(m)
```

##16 Team Wins and Losses (all matches with opposing IPL team)
The function below computes and plot the number of wins and losses in a head-on
confrontation between 2 IPL teams
```{python winsLosses, cache=TRUE, fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Chennai Super Kings-Delhi Daredevils-allMatches.csv")
csk_dd_matches = pd.read_csv(path)
yka.plotWinLossBetweenTeams(csk_dd_matches,'Chennai Super Kings','Delhi Daredevils')

```

##17 Team Wins by win type (all matches with opposing IPL team)
This function shows how the win happened whether by runs or by wickets
```{python winsType,cache=TRUE, fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Chennai Super Kings-Delhi Daredevils-allMatches.csv")
csk_dd_matches = pd.read_csv(path)
yka.plotWinsByRunOrWickets(csk_dd_matches,'Chennai Super Kings')

```

##18 Team Wins by toss decision (all matches with opposing IPL team)
This show how Rajasthan Royals fared when it chose to field on winning the toss
```{python winToss,cache=TRUE, fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Rajasthan Royals-Kings XI Punjab-allMatches.csv")
rr_kxip_matches = pd.read_csv(path)
yka.plotWinsbyTossDecision(rr_kxip_matches,'Rajasthan Royals',tossDecision='field')

```

##18 Team Wins by toss decision (all matches with opposing IPL team)
This plot shows how Mumbai Indians fared when it chose to bat on winning the toss
```{python winToss1,cache=TRUE, fig.width=10}
import pandas as pd
import os
import yorkpy.analytics as yka
dir1= "C:\\software\\cricket-package\\yorkpyIPLData\\data1"
path=os.path.join(dir1,"Mumbai Indians-Royal Challengers Bangalore-allMatches.csv")
mi_rcb_matches = pd.read_csv(path)
yka.plotWinsbyTossDecision(mi_rcb_matches,'Mumbai Indians',tossDecision='bat')

```
Feel free to  clone/download the code from  Github [yorkpy](https://github.com/tvganesh/yorkpy)

##Conclusion
This post included all functions between 2 IPL teams from the package yorkpy for IPL Twenty20 matches.As mentioned above the yaml match files have been already converted to dataframes and are available for download from Github at [yorkpyData](https://github.com/tvganesh/yorkpyData)


After having used Python and R for analytics, Machine Learning and Deep Learning, I have now realized that neither language is superior or inferior. Both have, some good packages and some that are not so well suited.  


**To be continued. Watch this space!**

You may also like 

1. [My book 'Deep Learning from first principles:Second Edition' now on Amazon](https://gigadom.in/2018/12/14/my-book-deep-learning-from-first-principlessecond-edition-now-on-amazon/)
2.[My book 'Practical Machine Learning in R and Python: Second edition' on Amazon](https://gigadom.in/2018/06/01/my-book-practical-machine-learning-in-r-and-python-second-edition-on-amazon/)
3. [Cricpy takes a swing at the ODIs](https://gigadom.in/2018/11/11/cricpy-takes-a-swing-at-the-odis/)
4. [Introducing cricket package yorkr: Part 1- Beaten by sheer pace!](https://gigadom.in/2016/04/02/introducing-cricket-package-yorkr-part-1-beaten-by-sheer-pace/)
5. [Big Data-1: Move into the big league:Graduate from Python to Pyspark](https://gigadom.in/2018/10/08/big-data-1-move-into-the-big-leaguegraduate-from-python-to-pyspark/)
6. [Simulating an Edge Shape in Android](https://gigadom.in/2013/06/07/simulating-an-edge-shape-in-android/)

To see all posts click [Index of posts](https://gigadom.in/aa-2/)

